authors:
- Sigmaprime Team
dependencies:
  community.general: '>=4.0.0'
  kubernetes.core: '>=2.0.0'
description: Ansible collection for installing and managing MicroK8s clusters
documentation: https://github.com/sigp/microk8s-ansible-collection/docs
homepage: https://github.com/sigp/microk8s-ansible-collection
issues: https://github.com/sigp/microk8s-ansible-collection/issues
license:
- Apache-2.0
name: microk8s
namespace: sigp
readme: README.md
repository: https://github.com/sigp/microk8s-ansible-collection
tags:
- kubernetes
- microk8s
- container
- orchestration
version: 1.0.5
