name: 'Kubernetes Kustomize Deployment'
description: 'Deploy applications using Kustomize with Helm support'
author: 'Sigmaprime'

inputs:
  environment:
    description: 'Deployment environment (dev/prod)'
    required: true
  app:
    description: 'Application name to deploy'
    required: true
  protocol:
    description: 'Preferred connection protocol (https/http)'
    required: false
    default: 'https'
  skip_tls_verify:
    description: 'Skip TLS verification (true/false)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Kubectl
      shell: bash
      env:
        KUBE_HOST: ${{ env.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
      run: |
        set -euo pipefail
        mkdir -p ~/.kube
        echo "${{ env.KUBE_CERTIFICATE }}" | base64 --decode > ca.crt
        kubectl config set-cluster k8s-cluster \
          --server="${{ inputs.protocol }}://${{ env.KUBE_HOST }}" \
          --certificate-authority=ca.crt \
          --embed-certs=true
        kubectl config set-credentials k8s-user \
          --token="${{ env.KUBE_TOKEN }}"
        kubectl config set-context k8s-context \
          --cluster=k8s-cluster \
          --user=k8s-user
        kubectl config use-context k8s-context
        
        echo "Verifying cluster connection..."
        kubectl get nodes --request-timeout=10s

    - name: Validate Kustomize Manifests
      shell: bash
      env:
        KUBE_HOST: ${{ env.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
      run: |
        KUSTOMIZE_PATH="./k8s/kustomize/${{ inputs.app }}/overlays/${{ inputs.environment }}"
        echo "Validating manifests in $KUSTOMIZE_PATH"
        kubectl kustomize --enable-helm "$KUSTOMIZE_PATH" --dry-run=server

    - name: Deploy with Kustomize+Helm
      shell: bash
      env:
        KUBE_HOST: ${{ env.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
      run: |
        KUSTOMIZE_PATH="./k8s/kustomize/${{ inputs.app }}/overlays/${{ inputs.environment }}"
        echo "Deploying from $KUSTOMIZE_PATH"
        kubectl kustomize --enable-helm "$KUSTOMIZE_PATH" | \
          kubectl apply -f - \
            --validate=${{ !inputs.skip_tls_verify }} \
            --timeout=120s \
            -o json | jq -r '"Deployed: " + (.items[].metadata.name | @text)'

    - name: Verify Deployment Status
      shell: bash
      env:
        KUBE_HOST: ${{ env.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
      run: |
        echo "Current deployment state:"
        kubectl get all -n ${{ inputs.app }} --show-labels
