---
# tasks file for admin role

- name: Add environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'HELLO_WORLD="hello world"'
    create: yes
  become: true
  

- name: Debug message
  ansible.builtin.debug:
    msg: 'sigp.k8s labelling role is running'

- name: Include dependencies tasks
  include_tasks: dependencies.yml



- name: Debug node_labeling_enabled value
  ansible.builtin.debug:
    var: node_labeling_enabled

- name: run labeling
  include_tasks: labeling.yml
  when: node_labeling_enabled | default(false)