---
# tasks file for admin role

- name: Include dependencies tasks
  include_tasks: dependencies.yml

- name: run labeling
  include_tasks: labeling.yml
  when: node_labeling_enabled | default(false)