---
# tasks file for admin role

- name: Add environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'HELLO_WORLD="hello world"'
    state: absent
  become: true
  


- name: Include dependencies tasks
  include_tasks: dependencies.yml



- name: Debug node_labeling_enabled value
  ansible.builtin.debug:
    var: node_labeling_enabled

- name: run labeling
  include_tasks: labeling.yml
  when: node_labeling_enabled | default(false)