name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - unstable # deploy to dev environment
      - stable # deploy to production environment

jobs:
  kubectl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .kube directory
        run: mkdir -p ~/.kube

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CERTIFICATE }}" | base64 --decode > ca.crt  # Decode if secret is base64 encoded
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          kubectl config set-cluster microk8s --certificate-authority=ca.crt

      - name: List pods
        uses: actions-hub/kubectl@master
        with:
          args: get pods --insecure-skip-tls-verify
        env:
          KUBECONFIG: ~/.kube/config
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}