---
# defaults file for sigp.k8s.github-actions

# Namespace configuration
github_actions_namespace: github-actions
github_actions_service_account: github-actions-sa

# Role configuration
github_actions_role_name: pod-reader
github_actions_role_binding_name: github-actions-pod-reader

# Target namespaces for RoleBindings
github_actions_target_namespaces:
  - default
  - lynx
  - rbuilder
  # - helix

# ClusterRoleBinding configuration
github_actions_cluster_role_binding_name: github-actions-cluster-admin
github_actions_cluster_role_name: cluster-admin
github_actions_enable_cluster_admin: false