name: 'Kubernetes Deployment'
description: 'Deploy applications to Kubernetes using Kustomize with environment-specific configuration'
author: 'Sigmaprime'

inputs:
  environment:
    description: 'Deployment environment (dev/prod)'
    required: true
  app:
    description: 'Application name to deploy'
    required: true
  protocol:
    description: 'Preferred connection protocol (https/http)'
    required: false
    default: 'https'
  skip_tls_verify:
    description: 'Skip TLS verification (true/false)'
    required: false 
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Verify CA Certificate
      shell: bash
      run: |
        echo "${{ env.KUBE_CERTIFICATE }}" | base64 --decode > ca.crt
        if [[ ! -s ca.crt ]]; then
          echo "Error: CA certificate is empty"
          exit 1
        fi
        openssl x509 -in ca.crt -text -noout

    - name: Determine Protocol
      if: ${{ inputs.protocol == '' }}
      id: check_protocol
      shell: bash
      run: |
        # Simplified protocol detection logic
        if curl -k -I "https://${{ env.KUBE_HOST }}" &> /dev/null; then
          echo "protocol=https" >> $GITHUB_OUTPUT
        else
          echo "protocol=http" >> $GITHUB_OUTPUT
        fi

    - name: Debug working directory
      shell: bash
      run: |
        echo "Current working directory: $(pwd)"
        echo "Contents of the directory:"
        ls -la

    - name: Execute kubectl command
      uses: actions-hub/kubectl@master
      with:
          args: ${{ inputs.command }}  ${{ inputs.skip_tls_verify == 'true' && '--insecure-skip-tls-verify' || '' }} ${{ inputs.args }} 
      env:
        KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
        KUBE_HOST: ${{ env.KUBE_HOST }}
        KUBE_TOKEN: ${{ env.KUBE_TOKEN }}