name: 'Kubectl Command'
description: 'Execute kubectl commands with pre-configured authentication'
author: 'Sigmaprime'

inputs:
  working_directory:
    description: 'Directory to run command from'
    required: false
    default: ''
  command:
    description: 'Main kubectl command (apply, delete, get, etc.)'
    required: true
  args:
    description: 'Additional command arguments'
    required: false
    default: ''
  skip_tls_verify:
    description: 'Skip TLS verification (true/false)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:

    - name: Debug Environment Variables
      shell: bash
      run: |
        echo "KUBE_HOST: ${{ env.KUBE_HOST }}" | sed 's/./& /g'
        echo "KUBE_TOKEN: ${{ env.KUBE_TOKEN }}" 
        echo "KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}"
        echo "KUBE_CONFIG: ${{ env.KUBE_CONFIG }}"


    - name: Setup kubectl config
      shell: bash
      run: |
        echo "${{ env.KUBE_CERTIFICATE }}" | base64 --decode > ca.crt
        mkdir -p ~/.kube
        echo "${{ env.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
        kubectl config set-cluster microk8s --certificate-authority=ca.crt
      env:
        KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
        KUBE_CONFIG: ${{ env.KUBE_CONFIG }}

    - name: Change directory
      if: ${{ inputs.working_directory != '' }}
      shell: bash
      run: cd ${{ inputs.working_directory }}

    - name: Debug working directory
      shell: bash
      run: |
        echo "Current working directory: $(pwd)"
        echo "Contents of the directory:"
        ls -la

    - name: Execute kubectl command
      uses: actions-hub/kubectl@master
      with:
          args: ${{ inputs.command }}  ${{ inputs.skip_tls_verify == 'true' && '--insecure-skip-tls-verify' || '' }} ${{ inputs.args }} 
      env:
        KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
        KUBE_HOST: ${{ env.KUBE_HOST }}
        KUBE_TOKEN: ${{ env.KUBE_TOKEN }}