---
# Common configuration tasks for all MicroK8s nodes

- name: Verify k8s_master group exists
  assert:
    that:
      - groups['k8s_master'] is defined
    fail_msg: "No k8s_master group defined in inventory"
    success_msg: "k8s_master group exists"

- name: Initialize join_commands dictionary
  set_fact:
    join_commands: {}

- name: Generate unique join command for each worker
  command: microk8s add-node --format yaml
  register: join_command_raw
  delegate_to: "{{ microk8s_primary }}"
  changed_when: false
  ignore_errors: true
  when: inventory_hostname in groups['k8s_worker']
  loop: "{{ groups['k8s_worker'] }}"
  loop_control:
    loop_var: worker_host
    label: "Generating for {{ worker_host }}"

- name: Store worker join commands
  set_fact:
    join_commands: "{{ join_commands | combine({worker_host: join_command_raw.results[ansible_loop.index0].stdout | from_yaml}) }}"
  when:
    - join_command_raw.results[ansible_loop.index0].stdout is defined
    - inventory_hostname in groups['k8s_worker']
  loop: "{{ groups['k8s_worker'] }}"
  loop_control:
    loop_var: worker_host
    index_var: ansible_loop

- name: Debug join commands
  debug:
    var: join_commands

- name: Debug full join command structure
  debug:
    var: join_command
    verbosity: 1

- name: Debug raw join command output
  debug:
    var: join_command_raw.stdout
    verbosity: 1
  changed_when: false

- name: Enable MicroK8s features
  command: "microk8s enable {{ item }}"
  become: true
  loop: "{{ microk8s_features }}"
  register: enable_features
  when: inventory_hostname in groups['k8s_master']
  changed_when: "'is already enabled' not in enable_features.stdout"

- name: Configure git safe directory (workaround for known issue)
  command: git config --global --add safe.directory /snap/microk8s/current/addons/community/.git

- name: Create bash aliases for MicroK8s
  block:
    - name: Ensure .bash_aliases exists
      file:
        path: "/home/{{ microk8s_user }}/.bash_aliases"
        state: touch
        owner: "{{ microk8s_user }}"
        group: "{{ microk8s_user }}"

    - name: Add microk8s kubectl alias
      lineinfile:
        path: "/home/{{ microk8s_user }}/.bash_aliases"
        line: "alias mk='microk8s kubectl'"
        regexp: '^alias mk='
        state: present

    - name: Add microk8s helm alias
      lineinfile:
        path: "/home/{{ microk8s_user }}/.bash_aliases"
        line: "alias mh='microk8s helm'"
        regexp: '^alias mh='
        state: present

# - name: Source the .bashrc file
#   command: "source /home/{{ microk8s_user }}/.bashrc"
#   args:
#     executable: /bin/bash
#   when: false

# TODO
# FAILED! => {"changed": false, "cmd": "source /home/ubuntu/.bashrc", "msg": "[Errno 2] No such file or directory: b'source'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
    