---
# tasks file for sigp.microk8s.configure

- name: Include common configuration tasks
  include_tasks: common.yml
  tags: configure

- name: Include master node tasks
  include_tasks: master.yml
  when: inventory_hostname in groups['k8s_master']
  tags: node_management

- name: Include worker node tasks
  include_tasks: worker.yml
  when: inventory_hostname in groups['k8s_worker']
  tags: node_management