---
- name: Include common configuration
  include_tasks: common.yml
  tags: always

- name: Verify join_command is available
  assert:
    that:
      - join_command is defined
    fail_msg: |
      join_command not available. Possible issues:
      - No k8s_master group in inventory
      - Primary node unreachable
      - microk8s not installed on primary
      - Debug info:
        Groups: {{ groups.keys() }}
        Primary: {{ microk8s_primary }}
        Raw output: {{ join_command_raw | default('Not generated') }}
  
- name: Debug join_command availability
  debug:
    var: join_command
    verbosity: 1

- name: Include master configuration
  include_tasks: master.yml
  when: inventory_hostname in groups['k8s_master']

- name: Include worker configuration
  include_tasks: worker.yml
  when: inventory_hostname in groups['k8s_worker']
# tasks file for sigp.microk8s.configure

- name: Include common configuration tasks
  include_tasks: common.yml
  tags: configure

- name: Include master node tasks
  include_tasks: master.yml
  when: inventory_hostname in groups['k8s_master']
  tags: node_management

- name: Include worker node tasks
  include_tasks: worker.yml
  when:
    - inventory_hostname in groups['k8s_worker']
    - not microk8s_sequential_join | default(false)
  tags: node_management

- name: Include sequential worker join tasks
  include_tasks: sequential_join.yml
  when:
    - inventory_hostname in groups['k8s_worker']
    - microk8s_sequential_join | default(false)
  tags: node_management