---
# Master node specific configuration tasks

- name: Generate join command on primary node
  command: microk8s add-node
  register: join_command
  delegate_to: "{{ microk8s_primary }}"
  run_once: true

- name: Remove node from cluster
  command: "microk8s remove-node {{ item }}"
  become: true
  loop: "{{ microk8s_nodes_to_remove }}"
  when: microk8s_nodes_to_remove is defined

- name: Check node status
  command: microk8s kubectl get nodes
  register: node_status
  changed_when: false