---

- name: Enable MicroK8s features
  command: "microk8s enable {{ item }}"
  become: true
  loop: "{{ microk8s_features }}"
  register: enable_features
  when: inventory_hostname in groups['k8s_master']
  changed_when: "'is already enabled' not in enable_features.stdout"
  
- name: Join master node to cluster
  block:
    - name: Generate fresh join token
      command: microk8s add-node --format yaml
      register: join_command
      delegate_to: "{{ microk8s_primary }}"
      changed_when: false
      retries: 3
      delay: 5
      until: join_command.rc == 0 and join_command.stdout != ''

    - name: Join as master node
      command: >
        microk8s join 
        {{ join_command.stdout | from_yaml | json_query('ip') }}:
        {{ join_command.stdout | from_yaml | json_query('port') }}/
        {{ join_command.stdout | from_yaml | json_query('token') }}/
        {{ join_command.stdout | from_yaml | json_query('hash') }}
      register: join_result
      retries: 3
      delay: 10
      until: join_result.rc == 0

    - name: Verify joined successfully
      command: microk8s kubectl get nodes -o wide
      register: node_list
      delegate_to: "{{ microk8s_primary }}"
      changed_when: false
      failed_when: "'{{ inventory_hostname }}' not in node_list.stdout"
      retries: 5
      delay: 15

  when: inventory_hostname in groups['k8s_master'] and inventory_hostname != microk8s_primary