---
# Worker node specific configuration tasks

- name: Join worker node to cluster
  command: "microk8s join {{ join_command.urls[0] }} --worker"
  when:
    - inventory_hostname in groups['k8s_worker']
    - join_command is defined
    - join_command.urls is defined
  

- name: Check node status
  command: microk8s kubectl get nodes
  register: node_status
  changed_when: false