---
# Worker node specific configuration tasks

- name: Join worker node to cluster
  command: "{{ join_command.stdout_lines[0] }}"
  

- name: Check node status
  command: microk8s kubectl get nodes
  register: node_status
  changed_when: false