---
# Worker node specific configuration tasks

- name: Join worker node to cluster
  command: "{{ join_command.stdout_lines[0] }}"
  when:
    - inventory_hostname in groups['k8s_worker']
    - join_command is defined
    - join_command.stdout_lines[0] is defined
  

- name: Check node status
  command: microk8s kubectl get nodes
  register: node_status
  changed_when: false