---
# handlers file for configure
  - name: restart ntp
    become: true
    ansible.builtin.service:
      name: ntp
      state: restarted

  - name: restart microk8s
    become: true
    ansible.builtin.reboot: