name: Reusable Kubectl Commands

on:
  push:
    paths:
      - 'k8s/**'
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory containing kustomize/helm files'
        required: true
        type: string
      kubectl_command:
        description: 'Main kubectl command (apply, delete, etc.)'
        required: true
        type: string
      command_args:
        description: 'Additional arguments for the command'
        required: false
        type: string
        default: ''
      skip_tls_verify:
        description: 'Skip TLS verification'
        required: false
        type: boolean
        default: false

jobs:
  kubectl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .kube directory
        run: mkdir -p ~/.kube

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CERTIFICATE }}" | base64 --decode > ca.crt
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          kubectl config set-cluster microk8s --certificate-authority=ca.crt

      - name: Change to working directory
        if: ${{ inputs.working_directory != '' }}
        run: cd ${{ inputs.working_directory }}

      - name: Execute kubectl command
        uses: actions-hub/kubectl@master
        with:
          args: ${{ inputs.kubectl_command }} ${{ inputs.command_args }} ${{ inputs.skip_tls_verify && '--insecure-skip-tls-verify' || '' }}
        env:
          KUBECONFIG: ~/.kube/config
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}